Repository Friend-LGA/msu_course_cpp_323_2022, pull requests merged in 2022-10, with the labels that each got.

#39 matveev_vladimir/task_02
  matveev_vladimir/README.md
  matveev_vladimir/graph.cpp
  matveev_vladimir/hello_world.cpp
  matveev_vladimir/screenshot.png
Labels: task_02

#34 stafeev_artem/task_02
  stafeev_artem/hello_world.cpp
  stafeev_artem/screenshot.png
  stafeev_artem/task_02.cpp
Labels: task_02

#22 chuvashov_egor/task_02
  chuvashov_egor/README.md
  chuvashov_egor/graph.cpp
  chuvashov_egor/hello_world.cpp
  chuvashov_egor/screenshot.png
Labels: task_02

#40 kovalenko_lev/task_02
  kovalenko_lev/Makefile
  kovalenko_lev/edge.hpp
  kovalenko_lev/graph.hpp
  kovalenko_lev/hello_world.cpp
  kovalenko_lev/main.cpp
  kovalenko_lev/vertex.hpp
Labels: task_02

#55 afanasev_nikita/task_02
  afanasev_nikita/hello_world.cpp
  afanasev_nikita/prog
  afanasev_nikita/prog.cpp
Labels: task_02

#8 zhang_xinyu/task_01
  zhang_xinyu/README.md
  zhang_xinyu/hello_world.cpp
  zhang_xinyu/screenshot.png
Labels: task_01

#38 mamedov_timur/task_02
  mamedov_timur/README.md
  mamedov_timur/graph.cpp
  mamedov_timur/hello_world.cpp
  mamedov_timur/screenshot.png
Labels: task_02

#54 kucherov_sergeev/task_03
  kucherov_sergeev/run
Labels: task_03

#48 fedotov_chuvashov/task_03
  fedotov_yaroslav/graph.cpp
  fedotov_yaroslav/graph.hpp
  fedotov_yaroslav/graph.json
  fedotov_yaroslav/main.cpp
  fedotov_yaroslav/printing.cpp
  fedotov_yaroslav/printing.hpp
Labels: task_03

#68 mao_yulong/task_01
  mao_yulong/README.md
  mao_yulong/hello_world.cpp
  mao_yulong/screenshot.png
Labels: task_01

#57 matveev_burikova/task_03
  burikova_anna/graph.cpp
  burikova_anna/graph.json
Labels: task_03

#33 antyukhov_nikita/task_02
  antyukhov_nikita/graph_gen.cpp
  antyukhov_nikita/hello_world.cpp
Labels: task_02

#66 afanasev_nikita/task_03
  afanasev_nikita/Makefile
  afanasev_nikita/graph.json
  afanasev_nikita/prog
  afanasev_nikita/prog.cpp
Labels: task_03

#1 krymskiy_sviatoslav/task_01
  krymskiy_sviatoslav/README.md
  krymskiy_sviatoslav/hello_world.cpp
  krymskiy_sviatoslav/screenshot.png
Labels: task_01

#83 kuznetsov_alexey/task_01
  kuznetsov_alexey/README.md
  kuznetsov_alexey/hello_world.cpp
  kuznetsov_alexey/screenshot.png
Labels: task_01

#53 mamedov_antyukhov/task_03
  mamedov_timur/Makefile
  mamedov_timur/README.md
  mamedov_timur/graph.cpp
  mamedov_timur/graph.hpp
  mamedov_timur/graph.json
  mamedov_timur/main.cpp
  mamedov_timur/printing.cpp
  mamedov_timur/printing.hpp
Labels: task_03

#59 tsybina_kovalenko/task_03
  tsybina_olga/Makefile
  tsybina_olga/graph.json
  tsybina_olga/graph_generation.cpp
Labels: task_03

#76 krymskiy_sviatoslav/task_02
  krymskiy_sviatoslav/Makefile
  krymskiy_sviatoslav/graph_generator.cpp
  krymskiy_sviatoslav/graph_generator.hpp
  krymskiy_sviatoslav/hello_world.cpp
Labels: task_02

#64 matveev_burikova/task_04
  matveev_burikova/graph.cpp
  matveev_burikova/graph.json
Labels: task_04

#75 krymskiy_sviatoslav/task_03
  krymskiy_sviatoslav/Makefile
  krymskiy_sviatoslav/graph.json
  krymskiy_sviatoslav/graph_generator.cpp
  krymskiy_sviatoslav/graph_generator.hpp
  krymskiy_sviatoslav/printing.cpp
  krymskiy_sviatoslav/printing.hpp
Labels: task_03
