Repository Friend-LGA/msu_course_cpp_323_2022, pull requests merged in 2022-12, with the labels that each got.

#116 afanasev_krymskiy/task_07
  afanasev_krymskiy/graph_generation_controller.cpp
  afanasev_krymskiy/graph_generation_controller.hpp
  afanasev_krymskiy/logger.cpp
  afanasev_krymskiy/logger.hpp
  afanasev_krymskiy/main.cpp
Labels: task_07

#121 kucherov_sergeev/task_07
  kucherov_sergeev/graph_generation_controller.cpp
  kucherov_sergeev/graph_generation_controller.hpp
  kucherov_sergeev/graph_generator.cpp
  kucherov_sergeev/logger.cpp
  kucherov_sergeev/logger.hpp
  kucherov_sergeev/main.cpp
  kucherov_sergeev/makefile
Labels: task_07

#106 matveev_burikova/task_07
  matveev_burikova/graph_generation_controller.cpp
  matveev_burikova/graph_generation_controller.hpp
  matveev_burikova/graph_generator.cpp
  matveev_burikova/logger.cpp
  matveev_burikova/logger.hpp
  matveev_burikova/main.cpp
Labels: task_07

#103 kuzminskiy_stafeev/task_07
  kuzminskiy_stafeev/graph_generation_controller.cpp
  kuzminskiy_stafeev/graph_generation_controller.hpp
  kuzminskiy_stafeev/graph_logger.cpp
  kuzminskiy_stafeev/graph_logger.hpp
  kuzminskiy_stafeev/main.cpp
  kuzminskiy_stafeev/makefile
Labels: task_07

#104 fedotov_chuvashov/task_07
  fedotov_chuvashov/graph_generation_controller.cpp
  fedotov_chuvashov/graph_generation_controller.hpp
  fedotov_chuvashov/graph_generator.cpp
  fedotov_chuvashov/graph_generator.hpp
  fedotov_chuvashov/logger.cpp
  fedotov_chuvashov/logger.hpp
  fedotov_chuvashov/main.cpp
Labels: task_07

#113 hong_chengyong/task_01
  hong_chengyong/README.md
  hong_chengyong/Screenshot.png
  hong_chengyong/hello_world.cpp
Labels: task_01

#109 mamedov_antyukhov/task 07
  mamedov_antyukhov/Makefile
  mamedov_antyukhov/graph_generation_controller.cpp
  mamedov_antyukhov/graph_generation_controller.hpp
  mamedov_antyukhov/graph_generator.cpp
  mamedov_antyukhov/logger.cpp
  mamedov_antyukhov/logger.hpp
  mamedov_antyukhov/main.cpp
Labels: task_07

#120 zhang_xinyu/task_04
  zhang_xinyu/a.out
  zhang_xinyu/graph.cpp
  zhang_xinyu/graph.json
Labels: task_04

#125 kuznetsov_sirbu/task_05
  kuznetsov_alexey/graph.cpp
  kuznetsov_alexey/graph.json
  kuznetsov_sirbu/config.hpp
  kuznetsov_sirbu/graph.cpp
  kuznetsov_sirbu/graph.hpp
  kuznetsov_sirbu/graph_generator.cpp
  kuznetsov_sirbu/graph_generator.hpp
  kuznetsov_sirbu/graph_json_printing.cpp
  kuznetsov_sirbu/graph_json_printing.hpp
  kuznetsov_sirbu/logger.cpp
  kuznetsov_sirbu/logger.hpp
  kuznetsov_sirbu/main.cpp
  kuznetsov_sirbu/printing.cpp
  kuznetsov_sirbu/printing.hpp
Labels: task_05

#114 hong_chengyong/task_02
  hong_chengyong/README.md
  hong_chengyong/Screenshot.png
  hong_chengyong/graph.hpp
  hong_chengyong/hello_world.cpp
  hong_chengyong/main.cpp
Labels: task_02

#126 kuznetsov_sirbu/task_06
  kuznetsov_sirbu/config.hpp
  kuznetsov_sirbu/graph_generator.cpp
  kuznetsov_sirbu/graph_generator.hpp
  kuznetsov_sirbu/main.cpp
Labels: task_06

#127 kuznetsov_sirbu/task_07
  kuznetsov_sirbu/graph_generation_controller.cpp
  kuznetsov_sirbu/graph_generation_controller.hpp
  kuznetsov_sirbu/logger.cpp
  kuznetsov_sirbu/logger.hpp
  kuznetsov_sirbu/main.cpp
  kuznetsov_sirbu/printing.cpp
Labels: task_07

#130 kuznetsov_sirbu/task_08
  kuznetsov_sirbu/graph.cpp
  kuznetsov_sirbu/graph.hpp
  kuznetsov_sirbu/graph_generation_controller.cpp
  kuznetsov_sirbu/graph_generation_controller.hpp
  kuznetsov_sirbu/graph_generator.cpp
  kuznetsov_sirbu/graph_generator.hpp
  kuznetsov_sirbu/graph_json_printing.cpp
  kuznetsov_sirbu/graph_json_printing.hpp
  kuznetsov_sirbu/interfaces/i_edge.hpp
  kuznetsov_sirbu/interfaces/i_graph.hpp
  kuznetsov_sirbu/interfaces/i_vertex.hpp
  kuznetsov_sirbu/interfaces/i_worker.hpp
  kuznetsov_sirbu/main.cpp
  kuznetsov_sirbu/printing.cpp
  kuznetsov_sirbu/printing.hpp
Labels: task_08

#136 hong_chengyong/task_03
  hong_chengyong/README.md
  hong_chengyong/graph.hpp
  hong_chengyong/graph.json
  hong_chengyong/main.cpp
Labels: task_03

#138 zhang _xinyu/task_06
  zhang_xinyu/graph_generator.cpp
  zhang_xinyu/graph_generator.hpp
  zhang_xinyu/graph_printing.cpp
  zhang_xinyu/makefile
Labels: task_06
