Repository Friend-LGA/msu_course_cpp_323_2022, pull requests merged in 2022-11, with the labels that each got.

#79 kucherov_sergeev/task_04
  kucherov_sergeev/graph.json
  kucherov_sergeev/graph_generator.cpp
Labels: task_04

#69 kuzminskiy_stafeev/task_04
  kuzminskiy_stafeev/gen_graph.cpp
  kuzminskiy_stafeev/graph.cpp
  kuzminskiy_stafeev/graph.hpp
  kuzminskiy_stafeev/graph.json
  kuzminskiy_stafeev/graph_generator.cpp
  kuzminskiy_stafeev/graph_generator.hpp
  kuzminskiy_stafeev/graph_json_printing.cpp
  kuzminskiy_stafeev/graph_json_printing.hpp
  kuzminskiy_stafeev/graph_printing.cpp
  kuzminskiy_stafeev/graph_printing.hpp
  kuzminskiy_stafeev/main.cpp
  kuzminskiy_stafeev/makefile
Labels: task_04

#85 afanasev_krymskiy/task_04
  afanasev_krymskiy/graph.json
  afanasev_krymskiy/prog.cpp
Labels: task_04

#81 mamedov_antyukhov/task_04
  mamedov_antyukhov/Makefile
  mamedov_antyukhov/graph.cpp
  mamedov_antyukhov/graph.hpp
  mamedov_antyukhov/graph.json
  mamedov_antyukhov/graph_generator.cpp
  mamedov_antyukhov/graph_generator.hpp
  mamedov_antyukhov/main.cpp
  mamedov_antyukhov/printing.cpp
  mamedov_antyukhov/printing.hpp
Labels: task_04

#80 fedotov_chuvashov/task_04
  fedotov_chuvashov/graph.cpp
  fedotov_chuvashov/graph.hpp
  fedotov_chuvashov/graph.json
  fedotov_chuvashov/graph_generator.cpp
  fedotov_chuvashov/graph_generator.hpp
  fedotov_chuvashov/main.cpp
  fedotov_chuvashov/printing.cpp
  fedotov_chuvashov/printing.hpp
Labels: task_04

#86 kuzminskiy_stafeev/task_05
  .gitignore
  kuzminskiy_stafeev/config.hpp
  kuzminskiy_stafeev/graph.cpp
  kuzminskiy_stafeev/graph.hpp
  kuzminskiy_stafeev/graph.json
  kuzminskiy_stafeev/graph_generator.cpp
  kuzminskiy_stafeev/graph_generator.hpp
  kuzminskiy_stafeev/graph_json_printing.cpp
  kuzminskiy_stafeev/graph_json_printing.hpp
  kuzminskiy_stafeev/graph_logger.cpp
  kuzminskiy_stafeev/graph_logger.hpp
  kuzminskiy_stafeev/graph_printing.cpp
  kuzminskiy_stafeev/graph_printing.hpp
  kuzminskiy_stafeev/main.cpp
  kuzminskiy_stafeev/makefile
Labels: task_05

#87 matveev_burikova/task_05
  .gitignore
  matveev_burikova/config.hpp
  matveev_burikova/graph.cpp
  matveev_burikova/graph.hpp
  matveev_burikova/graph.json
  matveev_burikova/graph_generator.cpp
  matveev_burikova/graph_generator.hpp
  matveev_burikova/graph_json_printing.cpp
  matveev_burikova/graph_json_printing.hpp
  matveev_burikova/graph_printing.cpp
  matveev_burikova/graph_printing.hpp
  matveev_burikova/logger.cpp
  matveev_burikova/logger.hpp
  matveev_burikova/main.cpp
Labels: task_05

#78 zhang_xinyu/task_02_2
  zhang_xinyu/graph.cpp
  zhang_xinyu/hello_world.cpp
Labels: task_02

#92 afanasev_krymskiy/task_05
  afanasev_krymskiy/Makefile
  afanasev_krymskiy/config.hpp
  afanasev_krymskiy/graph.cpp
  afanasev_krymskiy/graph.hpp
  afanasev_krymskiy/graph.json
  afanasev_krymskiy/graph_generator.cpp
  afanasev_krymskiy/graph_generator.hpp
  afanasev_krymskiy/graph_json_printing.cpp
  afanasev_krymskiy/graph_json_printing.hpp
  afanasev_krymskiy/graph_printing.cpp
  afanasev_krymskiy/graph_printing.hpp
  afanasev_krymskiy/logger.cpp
  afanasev_krymskiy/logger.hpp
  afanasev_krymskiy/main.cpp
  afanasev_krymskiy/prog.cpp
Labels: task_05

#89 kucherov_sergeev/task_05
  .gitignore
  kucherov_sergeev/config.hpp
  kucherov_sergeev/graph.cpp
  kucherov_sergeev/graph.hpp
  kucherov_sergeev/graph.json
  kucherov_sergeev/graph_generator.cpp
  kucherov_sergeev/graph_generator.hpp
  kucherov_sergeev/graph_json_printing.cpp
  kucherov_sergeev/graph_json_printing.hpp
  kucherov_sergeev/graph_printing.cpp
  kucherov_sergeev/graph_printing.hpp
  kucherov_sergeev/logger.cpp
  kucherov_sergeev/logger.hpp
  kucherov_sergeev/main.cpp
  kucherov_sergeev/makefile
Labels: task_05

#90 fedotov_chuvashov/task_05
  .gitignore
  fedotov_chuvashov/config.hpp
  fedotov_chuvashov/graph.cpp
  fedotov_chuvashov/graph.hpp
  fedotov_chuvashov/graph.json
  fedotov_chuvashov/graph_generator.cpp
  fedotov_chuvashov/graph_generator.hpp
  fedotov_chuvashov/logger.cpp
  fedotov_chuvashov/logger.hpp
  fedotov_chuvashov/main.cpp
  fedotov_chuvashov/printing.cpp
  fedotov_chuvashov/printing.hpp
  fedotov_chuvashov/printing_json.cpp
  fedotov_chuvashov/printing_json.hpp
Labels: task_05

#84 tsybina_kovalenko/task_04
  tsybina_kovalenko/Makefile
  tsybina_kovalenko/graph.hpp
  tsybina_kovalenko/graph.json
  tsybina_kovalenko/graph_generator.hpp
  tsybina_kovalenko/main.cpp
  tsybina_kovalenko/printing.hpp
Labels: task_04

#60 sirbu_alexandra/task_02
  sirbu_alexandra/README.md
  sirbu_alexandra/graph.hpp
  sirbu_alexandra/hello_world.cpp
  sirbu_alexandra/main.cpp
  sirbu_alexandra/makefile
  sirbu_alexandra/screenshot.png
Labels: task_02

#98 fedotov_chuvashov/task_06
  fedotov_chuvashov/graph_generator.cpp
  fedotov_chuvashov/graph_generator.hpp
Labels: task_06

#102 afanasev_krymskiy/task_06
  .gitignore
  afanasev_krymskiy/Makefile
  afanasev_krymskiy/config.hpp
  afanasev_krymskiy/graph_generator.cpp
  afanasev_krymskiy/graph_generator.hpp
Labels: task_06

#91 kuzminskiy_stafeev/task_06
  kuzminskiy_stafeev/graph_generator.cpp
  kuzminskiy_stafeev/graph_generator.hpp
  kuzminskiy_stafeev/makefile
Labels: task_06

#99 matveev_burikova/task_06
  matveev_burikova/graph_generator.cpp
  matveev_burikova/graph_generator.hpp
Labels: task_06

#93 mamedov_antyukhov/task_05
  mamedov_antyukhov/Makefile
  mamedov_antyukhov/config.hpp
  mamedov_antyukhov/graph.cpp
  mamedov_antyukhov/graph.hpp
  mamedov_antyukhov/graph.json
  mamedov_antyukhov/graph_generator.cpp
  mamedov_antyukhov/graph_generator.hpp
  mamedov_antyukhov/graph_json_printing.cpp
  mamedov_antyukhov/graph_json_printing.hpp
  mamedov_antyukhov/graph_printing.cpp
  mamedov_antyukhov/graph_printing.hpp
  mamedov_antyukhov/logger.cpp
  mamedov_antyukhov/logger.hpp
  mamedov_antyukhov/main.cpp
Labels: task_05

#94 kuznetsov_alexey/task 02
  kuznetsov_alexey/graph.cpp
  kuznetsov_alexey/hello_world.cpp
Labels: task_02

#100 kucherov_sergeev/task_06
  kucherov_sergeev/graph_generator.cpp
  kucherov_sergeev/graph_generator.hpp
  kucherov_sergeev/graph_printing.cpp
  kucherov_sergeev/makefile
Labels: task_06

#107 mamedov_antyukhov/task_06
  mamedov_antyukhov/Makefile
  mamedov_antyukhov/graph_generator.cpp
  mamedov_antyukhov/graph_generator.hpp
  mamedov_antyukhov/main.cpp
Labels: task_06

#95 kuznetsov_alexey/task_03
  kuznetsov_alexey/graph.cpp
  kuznetsov_alexey/graph.json
Labels: task_03

#52 zhang_xinyu/task_03
  zhang_xinyu/a.out
  zhang_xinyu/graph.cpp
  zhang_xinyu/graph.json
Labels: task_03
